version: '3.8'
services:
  websocket-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - NACOS_SERVER_ADDR=nacos://127.0.0.1:8848?username=nacos&password=nacos
      - MUC_SERVICE_NAME=muc-service
      - BUSINESS_SERVICE_NAME=im-business-service
    depends_on:
      - nacos
    networks:
      - app-network

  nacos:
    image: nacos/nacos-server:v3.1.0
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge