apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-service-config
data:
  ENV: "production"
  NACOS_SERVER_ADDR: "nacos.nacos.svc.cluster.local:8848"
  NACOS_NAMESPACE: "production"
  MUC_SERVICE_NAME: "muc-service"
  BUSINESS_SERVICE_NAME: "im-business-service"
  WS_READ_BUFFER_SIZE: "2048"
  WS_WRITE_BUFFER_SIZE: "2048"
  WS_MAX_MESSAGE_SIZE: "1024"